name: Update Game Master

on:
    schedule:
        - cron: '0 */6 * * *' # Toutes les 6 heures
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Configure git
              run: |
                  git config user.name "pogo-bot"
                  git config user.email "bot@users.noreply.github.com"

            - name: Run Update Script
              run: npm run update # Ce script génère tes dossiers data/raw et data/api

            - name: Commit meta timestamp (main)
              run: |
                  if [[ -n $(git status --porcelain meta/) ]]; then
                    git add meta/
                    git commit -m "chore(meta): update last Game Master timestamp"
                    git push origin main
                  else
                    echo "No meta change"
                  fi

            - name: Deploy to api-dist branch
              run: |
                  if [[ -n $(git status --porcelain data/) ]]; then

                    mkdir -p /tmp/generated_data
                    cp -r data/* /tmp/generated_data/

                    git fetch origin api-dist || true
                    git checkout api-dist || git checkout --orphan api-dist

                    git rm -rf . > /dev/null
                    cp -r /tmp/generated_data/* .

                    git add .
                    git commit -m "Update Game Master Data - $(date +'%Y-%m-%d %H:%M')"
                    git push origin api-dist
                  else
                    echo "No data change"
                  fi
