name: Update Game Master

on:
    schedule:
        - cron: '0 */6 * * *'
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - run: npm install
            - run: npm run update

            - run: |
                  if [[ `git status --porcelain` ]]; then
                    git config user.name "pogo-bot"
                    git config user.email "bot@users.noreply.github.com"
                    git add .
                    git commit -m "Update Game Master"
                    git push
                  else
                    echo "No changes to commit"
                  fi
